
Lmod is automatically replacing "intel/2020.1.217" with "gcc/9.3.0".


Due to MODULEPATH changes, the following have been reloaded:
  1) blis/0.8.1          3) libfabric/1.10.1     5) ucx/1.8.0
  2) flexiblas/3.0.4     4) openmpi/4.0.3

/var/spool/slurmd/job544478/slurm_script: line 15: env/bin/activate: No such file or directory
r0 master: ng10302.narval.calcul.quebec
r0 Launching python script
All the allocated nodes: ng10302
step 100 on epoch 1
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 200 on epoch 2
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 300 on epoch 3
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 400 on epoch 4
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 500 on epoch 5
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 600 on epoch 6
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 700 on epoch 7
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 800 on epoch 8
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 900 on epoch 9
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 1000 on epoch 10
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 1100 on epoch 11
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 1200 on epoch 12
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 1300 on epoch 13
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 1400 on epoch 14
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 1500 on epoch 15
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 1600 on epoch 16
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 1700 on epoch 17
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 1800 on epoch 18
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 1900 on epoch 19
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 2000 on epoch 20
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 2100 on epoch 21
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 2200 on epoch 22
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 2300 on epoch 23
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 2400 on epoch 24
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 2500 on epoch 25
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 2600 on epoch 26
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 2700 on epoch 27
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 2800 on epoch 28
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 2900 on epoch 29
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 3000 on epoch 30
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 3100 on epoch 31
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 3200 on epoch 32
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 3300 on epoch 33
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 3400 on epoch 34
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 3500 on epoch 35
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 3600 on epoch 36
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 3700 on epoch 37
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 3800 on epoch 38
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 3900 on epoch 39
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 4000 on epoch 40
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 4100 on epoch 41
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 4200 on epoch 42
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 4300 on epoch 43
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 4400 on epoch 44
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 4500 on epoch 45
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 4600 on epoch 46
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 4700 on epoch 47
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 4800 on epoch 48
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 4900 on epoch 49
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 5000 on epoch 50
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 5100 on epoch 51
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 5200 on epoch 52
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 5300 on epoch 53
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 5400 on epoch 54
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 5500 on epoch 55
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 5600 on epoch 56
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 5700 on epoch 57
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 5800 on epoch 58
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 5900 on epoch 59
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 6000 on epoch 60
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 6100 on epoch 61
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 6200 on epoch 62
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 6300 on epoch 63
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 6400 on epoch 64
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 6500 on epoch 65
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 6600 on epoch 66
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 6700 on epoch 67
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 6800 on epoch 68
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 6900 on epoch 69
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 7000 on epoch 70
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 7100 on epoch 71
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 7200 on epoch 72
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 7300 on epoch 73
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 7400 on epoch 74
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 7500 on epoch 75
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 7600 on epoch 76
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 7700 on epoch 77
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 7800 on epoch 78
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 7900 on epoch 79
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 8000 on epoch 80
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 8100 on epoch 81
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 8200 on epoch 82
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 8300 on epoch 83
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 8400 on epoch 84
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 8500 on epoch 85
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 8600 on epoch 86
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 8700 on epoch 87
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 8800 on epoch 88
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 8900 on epoch 89
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 9000 on epoch 90
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 9100 on epoch 91
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 9200 on epoch 92
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 9300 on epoch 93
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 9400 on epoch 94
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 9500 on epoch 95
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 9600 on epoch 96
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 9700 on epoch 97
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 9800 on epoch 98
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 9900 on epoch 99
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 10000 on epoch 100
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 10100 on epoch 101
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 10200 on epoch 102
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 10300 on epoch 103
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 10400 on epoch 104
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 10500 on epoch 105
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 10600 on epoch 106
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 10700 on epoch 107
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 10800 on epoch 108
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 10900 on epoch 109
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 11000 on epoch 110
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 11100 on epoch 111
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 11200 on epoch 112
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 11300 on epoch 113
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 11400 on epoch 114
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 11500 on epoch 115
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 11600 on epoch 116
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 11700 on epoch 117
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 11800 on epoch 118
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 11900 on epoch 119
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 12000 on epoch 120
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 12100 on epoch 121
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 12200 on epoch 122
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 12300 on epoch 123
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 12400 on epoch 124
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 12500 on epoch 125
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 12600 on epoch 126
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 12700 on epoch 127
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 12800 on epoch 128
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 12900 on epoch 129
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 13000 on epoch 130
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 13100 on epoch 131
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 13200 on epoch 132
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 13300 on epoch 133
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 13400 on epoch 134
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 13500 on epoch 135
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 13600 on epoch 136
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 13700 on epoch 137
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 13800 on epoch 138
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 13900 on epoch 139
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 14000 on epoch 140
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 14100 on epoch 141
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 14200 on epoch 142
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 14300 on epoch 143
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 14400 on epoch 144
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 14500 on epoch 145
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 14600 on epoch 146
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 14700 on epoch 147
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 14800 on epoch 148
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 14900 on epoch 149
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 15000 on epoch 150
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 15100 on epoch 151
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 15200 on epoch 152
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 15300 on epoch 153
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 15400 on epoch 154
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 15500 on epoch 155
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 15600 on epoch 156
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 15700 on epoch 157
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 15800 on epoch 158
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 15900 on epoch 159
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 16000 on epoch 160
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 16100 on epoch 161
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 16200 on epoch 162
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 16300 on epoch 163
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 16400 on epoch 164
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 16500 on epoch 165
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 16600 on epoch 166
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 16700 on epoch 167
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 16800 on epoch 168
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 16900 on epoch 169
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 17000 on epoch 170
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 17100 on epoch 171
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 17200 on epoch 172
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 17300 on epoch 173
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 17400 on epoch 174
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 17500 on epoch 175
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 17600 on epoch 176
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 17700 on epoch 177
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 17800 on epoch 178
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 17900 on epoch 179
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 18000 on epoch 180
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 18100 on epoch 181
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 18200 on epoch 182
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 18300 on epoch 183
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 18400 on epoch 184
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 18500 on epoch 185
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 18600 on epoch 186
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 18700 on epoch 187
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 18800 on epoch 188
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 18900 on epoch 189
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 19000 on epoch 190
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 19100 on epoch 191
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 19200 on epoch 192
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 19300 on epoch 193
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 19400 on epoch 194
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 19500 on epoch 195
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 19600 on epoch 196
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 19700 on epoch 197
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 19800 on epoch 198
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 19900 on epoch 199
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 20000 on epoch 200
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 20100 on epoch 201
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 20200 on epoch 202
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 20300 on epoch 203
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 20400 on epoch 204
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 20500 on epoch 205
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 20600 on epoch 206
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 20700 on epoch 207
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 20800 on epoch 208
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 20900 on epoch 209
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 21000 on epoch 210
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 21100 on epoch 211
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 21200 on epoch 212
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 21300 on epoch 213
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 21400 on epoch 214
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 21500 on epoch 215
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 21600 on epoch 216
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 21700 on epoch 217
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 21800 on epoch 218
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 21900 on epoch 219
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 22000 on epoch 220
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 22100 on epoch 221
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 22200 on epoch 222
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 22300 on epoch 223
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 22400 on epoch 224
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 22500 on epoch 225
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 22600 on epoch 226
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 22700 on epoch 227
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 22800 on epoch 228
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 22900 on epoch 229
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 23000 on epoch 230
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 23100 on epoch 231
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 23200 on epoch 232
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 23300 on epoch 233
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 23400 on epoch 234
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 23500 on epoch 235
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 23600 on epoch 236
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 23700 on epoch 237
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 23800 on epoch 238
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 23900 on epoch 239
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 24000 on epoch 240
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 24100 on epoch 241
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 24200 on epoch 242
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 24300 on epoch 243
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 24400 on epoch 244
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 24500 on epoch 245
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 24600 on epoch 246
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 24700 on epoch 247
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 24800 on epoch 248
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 24900 on epoch 249
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 25000 on epoch 250
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 25100 on epoch 251
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 25200 on epoch 252
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 25300 on epoch 253
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 25400 on epoch 254
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 25500 on epoch 255
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 25600 on epoch 256
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 25700 on epoch 257
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 25800 on epoch 258
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 25900 on epoch 259
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 26000 on epoch 260
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 26100 on epoch 261
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
step 26200 on epoch 262
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python: can't open file 'src/re_gold_qa_train.py': [Errno 2] No such file or directory
/var/spool/slurmd/job544478/slurm_script: line 75: 
python src/re_gold_qa_train.py \
	--mode re_qa_test \
	--model_path $SCRATCH/fold_1/pg-pgg-off-sim/ \
	--answer_checkpoint _0_answer_step_800 \
	--question_checkpoint _0_question_step_800 \
	--num_search_samples 8 \
	--batch_size 64 --gpu True \
	--ignore_unknowns True \
	--train zero-shot-extraction/relation_splits/train.very_small.0 \
	--dev zero-shot-extraction/relation_splits/test.0 \
	--gpu_device 0 \
	--seed 12321 \
	--prediction_file $SCRATCH/fold_1/pg-pgg-off-sim/pg_pgg_off_sim.test.predictions.step.800.csv
: No such file or directory
